version: '3'
services:
  app: 
    build: .
    container_name: workflowManagement-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/workflowmanagement
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workflowManagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes: 
  postgres_data: